name: Build and Run ScanCode Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3-pip curl jq
          pip3 install conan
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          conan profile detect
      
      - name: Create conan.lock file
        run: conan lock create conanfile.txt --lockfile-out=conan.lock

      - name: Install project dependencies with Conan
        run: |
          mkdir -p build
          conan install . --lockfile=conan.lock --output-folder=build --build=missing

      - name: Configure with CMake
        run: |
          cmake -Bbuild -S. -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cmake --build build

      - name: Package build output
        run: |
          tar -czf build-output.tar.gz -C build .

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: Build ${{ github.sha }}
          draft: false
          prerelease: false
          files: build-output.tar.gz

      - name: Prepare download URLs
        run: |
          echo "BUILD_DOWNLOAD_URL=https://github.com/${{ github.repository }}/releases/download/build-${{ github.sha }}/build-output.tar.gz" >> $GITHUB_ENV
          echo "SOURCE_DOWNLOAD_URL=https://github.com/${{ github.repository }}/archive/${{ github.sha }}.zip" >> $GITHUB_ENV

      - name: Prepare source code download URL
        run: |
          echo "SOURCE_DOWNLOAD_URL=https://github.com/${{ github.repository }}/archive/${{ github.sha }}.zip" >> $GITHUB_ENV

      # ------------------------------
      # 1. SCAN: Build Artifact
      # ------------------------------
      - name: Run scan_project.py on build artifact
        env:
          SCANCODEIO_URL: ${{ secrets.SCANCODEIO_URL }}
          SCANCODEIO_API_KEY: ${{ secrets.SCANCODEIO_API_KEY }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}-build
          PIPELINES: ${{ vars.PIPELINES }}
          INPUT_URLS: ${{ env.BUILD_DOWNLOAD_URL }}
        run: |
          cd scancode-io
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scan_project.py

      # ------------------------------
      # 2. SCAN: Source Code Archive
      # ------------------------------
      - name: Run scan_project.py on source code archive
        env:
          SCANCODEIO_URL: ${{ secrets.SCANCODEIO_URL }}
          SCANCODEIO_API_KEY: ${{ secrets.SCANCODEIO_API_KEY }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}-source
          PIPELINES: ${{ vars.PIPELINES }}
          INPUT_URLS: ${{ env.SOURCE_DOWNLOAD_URL }}
        run: |
          cd scancode-io
          python scan_project.py
